#include <bits/stdc++.h>
#include <windows.h>
#include <conio.h>

using namespace std;
int main(){
			system("color 2");
	int choose; 
	cout << "\tLICH TRINH LAM VIEC "<< endl;
	cout << "2.THU 2"<<endl;
	cout << "3.THU 3"<<endl;
	cout << "4.THU 4"<<endl;
	cout << "5.THU 5"<<endl;
	cout << "6.THU 6"<<endl;
	cout << "7.THU 7"<<endl;
	cout << "1.CHU NHAT"<<endl;
	cout << "CHOOSE : ";
	cin >> choose;
	system("cls");
	
	switch(choose){
		case 2 :
			cout <<"\tLICH TRINH LAM VIEC THU 2 "<<endl;
			cout <<"- Buoi Sang :"<<endl;
			cout <<"+ 5h30 -> 6h : Tap the duc\n\n";
			cout <<"+ 6h -> 6h30 : Ve sinh ca nhan\n\n";
			cout <<"+ 6h30 -> 7h : An sang\n\n";
			cout <<"+ 7h -> 8h30 : Setup Cryto\n\n";
			cout <<"+ 8h30 -> 11h30 : Learning C++\n\n";
			getch();
			cout <<" HOAN THANH -_-"<<endl;
			getch();
			system("cls");
			cout <<"- Buoi Trua :"<<endl;
			cout <<"+ 11h30 -> 12h : An trua\n\n";
			cout <<"+ 12h -> 13h30 : Sleep\n\n";
			cout <<"+ 13h30 -> 16h30 : Learning C#\n\n";
			cout <<"+ 16h30 -> 17h : Tap the duc\n\n";
			cout <<"+ 17h -> 17h30 : Ve sinh ca nhan\n\n";
			getch();
			cout <<" HOAN THANH -_-"<<endl;
			getch();
			system("cls");
			cout <<"- Buoi Toi :"<< endl;
			cout <<"+ 17h30 -> 18h : An toi\n\n";
			cout <<"+ 18h -> 19h : Relax\n\n";
			cout <<"+ 19h -> 22h : Learning Front-End\n\n";
			cout <<"+ 22h -> 23h : Ve sinh ca nhan\n\n";
			cout <<"+ 23h : Sleep\n\n";
			getch();
			cout <<" HOAN THANH -_-"<<endl;
			getch();
			break;
		case 3 :
			cout <<"\tLICH TRINH LAM VIEC THU 3 "<<endl;
			cout <<"- Buoi Sang :"<<endl;
			cout <<"+ 5h30 -> 6h : Tap the duc\n\n";
			cout <<"+ 6h -> 6h30 : Ve sinh ca nhan\n\n";
			cout <<"+ 6h30 -> 7h : An sang\n\n";
			cout <<"+ 7h -> 8h30 : Setup Cryto\n\n";
			cout <<"+ 8h30 -> 11h30 : Learning C++\n\n";
			getch();
			cout <<" HOAN THANH -_-"<<endl;
			getch();
			system("cls");
			cout <<"- Buoi Trua :"<<endl;
			cout <<"+ 11h30 -> 12h : An trua\n\n";
			cout <<"+ 12h -> 13h30 : Sleep\n\n";
			cout <<"+ 13h30 -> 16h30 : Learning C#\n\n";
			cout <<"+ 16h30 -> 17h : Tap the duc\n\n";
			cout <<"+ 17h -> 17h30 : Ve sinh ca nhan\n\n";
			getch();
			cout <<" HOAN THANH -_-"<<endl;
			getch();
			system("cls");
			cout <<"- Buoi Toi :"<< endl;
			cout <<"+ 17h30 -> 18h : An toi\n\n";
			cout <<"+ 18h -> 19h : Relax\n\n";
			cout <<"+ 19h -> 22h : Learning Front-End\n\n";
			cout <<"+ 22h -> 23h : Ve sinh ca nhan\n\n";
			cout <<"+ 23h : Sleep\n\n";
			getch();
			cout <<" HOAN THANH -_-"<<endl;
			getch();
			break;
		case 4 :
			cout <<"\tLICH TRINH LAM VIEC THU 4 "<<endl;
			cout <<"- Buoi Sang :"<<endl;
			cout <<"+ 5h30 -> 6h : Tap the duc\n\n";
			cout <<"+ 6h -> 6h30 : Ve sinh ca nhan\n\n";
			cout <<"+ 6h30 -> 7h : An sang\n\n";
			cout <<"+ 7h -> 8h30 : Setup Cryto\n\n";
			cout <<"+ 8h30 -> 11h30 : Learning C++\n\n";
			getch();
			cout <<" HOAN THANH -_-"<<endl;
			getch();
			system("cls");
			cout <<"- Buoi Trua :"<<endl;
			cout <<"+ 11h30 -> 12h : An trua\n\n";
			cout <<"+ 12h -> 13h30 : Sleep\n\n";
			cout <<"+ 13h30 -> 16h30 : Learning C#\n\n";
			cout <<"+ 16h30 -> 17h : Tap the duc\n\n";
			cout <<"+ 17h -> 17h30 : Ve sinh ca nhan\n\n";
			getch();
			cout <<" HOAN THANH -_-"<<endl;
			getch();
			system("cls");
			cout <<"- Buoi Toi :"<< endl;
			cout <<"+ 17h30 -> 18h : An toi\n\n";
			cout <<"+ 18h -> 19h : Relax\n\n";
			cout <<"+ 19h -> 22h : Learning Front-End\n\n";
			cout <<"+ 22h -> 23h : Ve sinh ca nhan\n\n";
			cout <<"+ 23h : Sleep\n\n";
			getch();
			cout <<" HOAN THANH -_-"<<endl;
			getch();
			break;
		case 5 :
			cout <<"\tLICH TRINH LAM VIEC THU 5 "<<endl;
			cout <<"- Buoi Sang :"<<endl;
			cout <<"+ 5h30 -> 6h : Tap the duc\n\n";
			cout <<"+ 6h -> 6h30 : Ve sinh ca nhan\n\n";
			cout <<"+ 6h30 -> 7h : An sang\n\n";
			cout <<"+ 7h -> 8h30 : Setup Cryto\n\n";
			cout <<"+ 8h30 -> 11h30 : Learning C++\n\n";
			getch();
			cout <<" HOAN THANH -_-"<<endl;
			getch();
			system("cls");
			cout <<"- Buoi Trua :"<<endl;
			cout <<"+ 11h30 -> 12h : An trua\n\n";
			cout <<"+ 12h -> 13h30 : Sleep\n\n";
			cout <<"+ 13h30 -> 16h30 : Learning C#\n\n";
			cout <<"+ 16h30 -> 17h : Tap the duc\n\n";
			cout <<"+ 17h -> 17h30 : Ve sinh ca nhan\n\n";
			getch();
			cout <<" HOAN THANH -_-"<<endl;
			getch();
			system("cls");
			cout <<"- Buoi Toi :"<< endl;
			cout <<"+ 17h30 -> 18h : An toi\n\n";
			cout <<"+ 18h -> 19h : Relax\n\n";
			cout <<"+ 19h -> 22h : Learning Front-End\n\n";
			cout <<"+ 22h -> 23h : Ve sinh ca nhan\n\n";
			cout <<"+ 23h : Sleep\n\n";
			getch();
			cout <<" HOAN THANH -_-"<<endl;
			getch();
			break;
		case 6 :
			cout <<"\tLICH TRINH LAM VIEC THU 6 "<<endl;
			cout <<"- Buoi Sang :"<<endl;
			cout <<"+ 5h30 -> 6h : Tap the duc\n\n";
			cout <<"+ 6h -> 6h30 : Ve sinh ca nhan\n\n";
			cout <<"+ 6h30 -> 7h : An sang\n\n";
			cout <<"+ 7h -> 8h30 : Setup Cryto\n\n";
			cout <<"+ 8h30 -> 11h30 : Learning C++\n\n";
			getch();
			cout <<" HOAN THANH -_-"<<endl;
			getch();
			system("cls");
			cout <<"- Buoi Trua :"<<endl;
			cout <<"+ 11h30 -> 12h : An trua\n\n";
			cout <<"+ 12h -> 13h30 : Sleep\n\n";
			cout <<"+ 13h30 -> 16h30 : Learning C#\n\n";
			cout <<"+ 16h30 -> 17h : Tap the duc\n\n";
			cout <<"+ 17h -> 17h30 : Ve sinh ca nhan\n\n";
			getch();
			cout <<" HOAN THANH -_-"<<endl;
			getch();
			system("cls");
			cout <<"- Buoi Toi :"<< endl;
			cout <<"+ 17h30 -> 18h : An toi\n\n";
			cout <<"+ 18h -> 19h : Relax\n\n";
			cout <<"+ 19h -> 22h : Learning Front-End\n\n";
			cout <<"+ 22h -> 23h : Ve sinh ca nhan\n\n";
			cout <<"+ 23h : Sleep\n\n";
			getch();
			cout <<" HOAN THANH -_-"<<endl;
			getch();
			break;
		case 7 :
			cout <<"\tLICH TRINH LAM VIEC THU 7 "<<endl;
			cout <<"- Buoi Sang :"<<endl;
			cout <<"+ 5h30 -> 6h : Tap the duc\n\n";
			cout <<"+ 6h -> 6h30 : Ve sinh ca nhan\n\n";
			cout <<"+ 6h30 -> 7h : An sang\n\n";
			cout <<"+ 7h -> 8h30 : Setup Cryto\n\n";
			cout <<"+ 8h30 -> 11h30 : Learning C++\n\n";
			getch();
			cout <<" HOAN THANH -_-"<<endl;
			getch();
			system("cls");
			cout <<"- Buoi Trua :"<<endl;
			cout <<"+ 11h30 -> 12h : An trua\n\n";
			cout <<"+ 12h -> 13h30 : Sleep\n\n";
			cout <<"+ 13h30 -> 16h30 : Learning C#\n\n";
			cout <<"+ 16h30 -> 17h : Tap the duc\n\n";
			cout <<"+ 17h -> 17h30 : Ve sinh ca nhan\n\n";
			getch();
			cout <<" HOAN THANH -_-"<<endl;
			getch();
			system("cls");
			cout <<"- Buoi Toi :"<< endl;
			cout <<"+ 17h30 -> 18h : An toi\n\n";
			cout <<"+ 18h -> 19h : Relax\n\n";
			cout <<"+ 19h -> 22h : Learning Front-End\n\n";
			cout <<"+ 22h -> 23h : Ve sinh ca nhan\n\n";
			cout <<"+ 23h : Sleep\n\n";
			getch();
			cout <<" HOAN THANH -_-"<<endl;
			getch();
			break;
		case 1 :
			cout <<"\tLICH TRINH LAM VIEC CHU NHAT "<<endl;
			cout <<"- Buoi Sang :"<<endl;
			cout <<"+ 5h30 -> 6h : Tap the duc\n\n";
			cout <<"+ 6h -> 6h30 : Ve sinh ca nhan\n\n";
			cout <<"+ 6h30 -> 7h : An sang\n\n";
			cout <<"+ 7h -> 8h30 : Setup Cryto\n\n";
			cout <<"+ 8h30 -> 11h30 : Learning C++\n\n";
			getch();
			cout <<" HOAN THANH -_-"<<endl;
			getch();
			system("cls");
			cout <<"- Buoi Trua :"<<endl;
			cout <<"+ 11h30 -> 12h : An trua\n\n";
			cout <<"+ 12h -> 13h30 : Sleep\n\n";
			cout <<"+ 13h30 -> 16h30 : Learning C#\n\n";
			cout <<"+ 16h30 -> 17h : Tap the duc\n\n";
			cout <<"+ 17h -> 17h30 : Ve sinh ca nhan\n\n";
			getch();
			cout <<" HOAN THANH -_-"<<endl;
			getch();
			system("cls");
			cout <<"- Buoi Toi :"<< endl;
			cout <<"+ 17h30 -> 18h : An toi\n\n";
			cout <<"+ 18h -> 19h : Relax\n\n";
			cout <<"+ 19h -> 22h : Learning Front-End\n\n";
			cout <<"+ 22h -> 23h : Ve sinh ca nhan\n\n";
			cout <<"+ 23h : Sleep\n\n";
			getch();
			cout <<" HOAN THANH -_-"<<endl;
			getch();
			break;
		default :
			cout << "EROR !!!!!!!"	;				
	}



	return 0;
}

